import 'package:freezed_annotation/freezed_annotation.dart';

part 'caption_track.freezed.dart';
part 'caption_track.g.dart';

/// One caption track, mirroring the sidecar's `CaptionTrack` field for field
/// (`protocol.md` §3.8).
///
/// **There is no URL here, and its absence is the contract.** A `timedtext`
/// address is signed, and the sidecar is what fetches it; [id] is an opaque
/// handle handed back to `captions.get`. Same reasoning as hard invariant 2 on a
/// second endpoint.
///
/// [id] rather than [languageCode] is the identity, because a language has up to
/// two tracks — `.en` manual and `a.en` auto-generated — and a code cannot tell
/// them apart. Session preference is remembered by language anyway (a user who
/// wants German wants German however it was produced), and that asymmetry is
/// deliberate: see `CaptionsController.preferredLanguage`.
@freezed
abstract class CaptionTrack with _$CaptionTrack {
  const CaptionTrack._();

  const factory CaptionTrack({
    required String id,
    required String languageCode,
    required String label,
    required bool isAutoGenerated,

    /// YouTube's own sub-name for the track, or `''`.
    ///
    /// How a channel distinguishes two tracks in one language — "Commentary",
    /// "Forced". Empty on every track measured so far, which is why the picker
    /// only draws it when it is not.
    @Default('') String trackName,

    /// What styling the track carries: `'plain'`, `'styled'` or `'karaoke'`.
    /// **`null` means "not asked", which is the state on the video-open path.**
    ///
    /// It cannot be read off the track list: the styling lives in the document,
    /// one fetch per track. `captions.list` runs alongside `video.info` (§3.8)
    /// and must not pay for it, so the caption menu is what asks, with
    /// `includeStyled`. A badge is never a reason to slow a video open.
    ///
    /// It is **not** the same question as [isAutoGenerated], and the sidecar is
    /// careful about that: every auto-generated track carries window geometry,
    /// so the obvious "does it have styling arrays" test marks every ASR track
    /// styled. The answer here is about `pens` alone.
    ///
    /// A string rather than an enum because it crosses the wire as one and the
    /// DTO mirrors the sidecar field for field; [styleBadge] is where it becomes
    /// a decision the UI can act on, including for a value this build has never
    /// heard of.
    String? styled,
    @Default(false) bool isTranslatable,
  }) = _CaptionTrack;

  factory CaptionTrack.fromJson(Map<String, Object?> json) => _$CaptionTrackFromJson(json);

  /// The word the picker badges this track with, or null for no badge.
  ///
  /// **An unrecognised value badges nothing rather than itself.** A sidecar
  /// newer than the app can send a category this build has never heard of, and
  /// a row that prints it raw would show the user a protocol token. Silence is
  /// the honest degradation — the same reasoning hard invariant 4 applies to an
  /// unknown renderer.
  String? get styleBadge => switch (styled) {
        // 'karaoke' => "🎤",//'Karaoke',
        // 'styled' => "🖌️",//'Styled',
        'karaoke' => 'Karaoke',
        'styled' => 'Styled',
        _ => null,
      };
}

/// `captions.get`'s result — one track as a subtitle document.
///
/// [format] is `'ass'` today and is carried rather than assumed: the body goes
/// straight to a subtitle demuxer, and a silent format change renders as nothing
/// at all rather than as an error.
@freezed
abstract class CaptionTrackContent with _$CaptionTrackContent {
  const CaptionTrackContent._();

  const factory CaptionTrackContent({
    required String trackId,
    required String languageCode,
    required String format,
    required String content,
    @Default(0) int cueCount,
  }) = _CaptionTrackContent;

  factory CaptionTrackContent.fromJson(Map<String, Object?> json) =>
      _$CaptionTrackContentFromJson(json);
}
