import 'package:freezed_annotation/freezed_annotation.dart';

part 'caption_track.freezed.dart';
part 'caption_track.g.dart';

/// One caption track, mirroring the sidecar's `CaptionTrack` field for field
/// (`protocol.md` §3.8).
///
/// **There is no URL here, and its absence is the contract.** A `timedtext`
/// address is signed, and the sidecar is what fetches it; [id] is an opaque
/// handle handed back to `captions.get`. Same reasoning as hard invariant 2 on a
/// second endpoint.
///
/// [id] rather than [languageCode] is the identity, because a language has up to
/// two tracks — `.en` manual and `a.en` auto-generated — and a code cannot tell
/// them apart. Session preference is remembered by language anyway (a user who
/// wants German wants German however it was produced), and that asymmetry is
/// deliberate: see `CaptionsController.preferredLanguage`.
@freezed
abstract class CaptionTrack with _$CaptionTrack {
  const CaptionTrack._();

  const factory CaptionTrack({
    required String id,
    required String languageCode,
    required String label,
    required bool isAutoGenerated,
    @Default(false) bool isTranslatable,
  }) = _CaptionTrack;

  factory CaptionTrack.fromJson(Map<String, Object?> json) => _$CaptionTrackFromJson(json);
}

/// `captions.get`'s result — one track as a subtitle document.
///
/// [format] is `'ass'` today and is carried rather than assumed: the body goes
/// straight to a subtitle demuxer, and a silent format change renders as nothing
/// at all rather than as an error.
@freezed
abstract class CaptionTrackContent with _$CaptionTrackContent {
  const CaptionTrackContent._();

  const factory CaptionTrackContent({
    required String trackId,
    required String languageCode,
    required String format,
    required String content,
    @Default(0) int cueCount,
  }) = _CaptionTrackContent;

  factory CaptionTrackContent.fromJson(Map<String, Object?> json) =>
      _$CaptionTrackContentFromJson(json);
}
