/// `RILL_CAPTIONS_PROBE=1` — task 17's measurements, from the real app.
///
/// Same family as `RILL_CONTROLS_PROBE`, and for the same reason: three of the
/// things this task has to answer are only observable against real libmpv in a
/// real window, and none of them is reachable from a widget test.
///
/// 1. **Does attaching a caption track rebuild the video output?** This is a
///    stop condition. A quality switch costs 0.55–12 s precisely because it
///    reopens the media (F19), and if `sub-add` did the same, captions would
///    have to become a per-open choice rather than a free toggle. The instrument
///    is F19's own: `VideoController.id` changes when the output is rebuilt.
/// 2. **Do captions survive a quality switch?** The switch *does* reopen, so
///    mpv drops external subtitle tracks with it. `MediaKitEngine.open` is
///    supposed to put the track back.
/// 3. **Can the bundled libass actually render what `ass.ts` emits?** mpv's own
///    track list is the answer — a document it rejected is not in it.
///
/// Unset, this costs one environment lookup at startup.
library;

import 'dart:async';
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../data/playback/engine.dart';
import '../../domain/playback_source.dart';
import '../captions_controller.dart';
import '../playback_controller.dart';
import 'settings_menu.dart';

void runCaptionsProbe(ProviderContainer container) {
  final mode = Platform.environment['RILL_CAPTIONS_PROBE'];
  if (mode != '1' && mode != 'synthetic') return;
  WidgetsBinding.instance.addPostFrameCallback(
    (_) => unawaited(mode == 'synthetic' ? _syntheticProbe(container) : _probe(container)),
  );
}

void _say(String line) => stderr.writeln('captions-probe: $line');

Future<void> _wait([int millis = 2000]) => Future<void>.delayed(Duration(milliseconds: millis));

/// mpv's own track list, as `type[*]:codec` per entry.
///
/// A diagnostics-only property read, off the UI isolate's critical path and
/// never polled — hard invariant 9's carve-out, the same one
/// `audio_delay_probe.dart` uses. It is the only way to see whether libass
/// *accepted* a document: a rejected one leaves the picture looking identical.
Future<String> _mpvTracks(PlaybackEngine engine) async {
  if (engine is! MediaKitEngine) return 'n/a';
  try {
    final count = await engine.diagnostics.getProperty('track-list/count');
    final n = int.tryParse(count) ?? 0;
    final out = <String>[];
    for (var i = 0; i < n; i++) {
      final type = await engine.diagnostics.getProperty('track-list/$i/type');
      final selected = await engine.diagnostics.getProperty('track-list/$i/selected');
      final codec = await engine.diagnostics.getProperty('track-list/$i/codec');
      out.add('$type${selected == 'yes' ? '*' : ''}:$codec');
    }
    return out.isEmpty ? '(none)' : out.join(' ');
  } on Object catch (e) {
    return 'unreadable ($e)';
  }
}

/// A document in exactly the shape `captions/ass.ts` emits, including one cue
/// carrying the positioning and colour overrides a YTT parser would produce.
const String _sampleAss = '''
[Script Info]
; Generated by Rill from YouTube timed text. Do not edit.
; source: asr en
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2.5,0,2,60,60,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.32,0:00:14.58,Default,,0,0,0,,[Music]
Dialogue: 0,0:00:14.60,0:00:21.80,Default,,0,0,0,,We\\Nare no strangers to
Dialogue: 0,0:00:21.80,0:00:40.00,Default,,0,0,0,,{\\an7\\pos(480,540)\\c&H0000FFFF}styled and positioned
''';

/// **The libmpv half of the measurement, with YouTube taken out of it.**
///
/// Whether `sub-add` rebuilds the video output is a question about media_kit and
/// the bundled libmpv, not about which URL is playing — so it needs no YouTube
/// stream, and on 2026-08-18 it could not have had one: every `googlevideo` URL
/// on this machine was refused (F20's poisoned bucket, at 100% rather than its
/// recorded ~30%, and `yt-dlp` was refused too). `av://lavfi:testsrc` is
/// generated locally by ffmpeg, so the same `Player`, the same `sub-add` and the
/// same libass run with nothing on the network.
///
/// What it cannot answer is anything about a caption document arriving over the
/// wire. That half is covered by driving the compiled sidecar directly.
Future<void> _syntheticProbe(ProviderContainer container) async {
  final engine = container.read(playbackEngineProvider);
  if (engine is! MediaKitEngine) {
    _say('FAILED synthetic mode needs the real engine');
    exit(1);
  }

  int? textureId() => engine.videoController.id.value;

  // A local file, from `RILL_CAPTIONS_MEDIA`.
  //
  // `av://lavfi:` would have been tidier — no file to make — but the bundled
  // libmpv does not register libavdevice (`avdevice_register_all` occurs 0 times
  // in the artefact, against 13 for `lavfi`), so the protocol is named and not
  // usable. Any file mpv can open works; the measurements are about `sub-add`,
  // not about the picture.
  final path = Platform.environment['RILL_CAPTIONS_MEDIA']?.trim();
  if (path == null || path.isEmpty) {
    _say('FAILED set RILL_CAPTIONS_MEDIA to a local video file');
    exit(1);
  }
  final variant = PlaybackVariant(
    videoUrl: path,
    height: 360,
    fps: 30,
    videoCodec: 'h264',
    audioCodec: 'none',
  );

  try {
    _say('synthetic mode: opening $path (no network)');
    await engine.open(variant);
    final deadline = DateTime.now().add(const Duration(seconds: 30));
    while (engine.position <= Duration.zero && DateTime.now().isBefore(deadline)) {
      await _wait(200);
    }
    if (engine.position <= Duration.zero) {
      _say('FAILED the local source did not start');
      exit(1);
    }

    // The same settle trap as `controls_probe`: media_kit frees and recreates
    // the texture ~1 s after an open, once the real size is known, so a baseline
    // taken any earlier reports every later comparison as a rebuild.
    await _wait(3000);
    var last = textureId();
    _say('playing. pos=${engine.position} texture=$last');
    _say('tracks before: ${await _mpvTracks(engine)}');

    void check(String label) {
      final now = textureId();
      _say('$label: texture=$now ${now == last ? 'UNCHANGED' : 'REBUILT'} '
          'pos=${engine.position} playing=${engine.playing}');
      last = now;
    }

    // --- 1. does attaching rebuild the output? -----------------------------
    final posBefore = engine.position;
    var started = DateTime.now();
    await engine.setSubtitle(_sampleAss);
    final attachMs = DateTime.now().difference(started).inMilliseconds;
    await _wait(1500);
    check('sub-add');
    _say('attach took $attachMs ms; position '
        '${posBefore.inSeconds}s -> ${engine.position.inSeconds}s');

    // --- 2. did libass accept it? ------------------------------------------
    final withSub = await _mpvTracks(engine);
    _say('tracks after attach: $withSub');
    _say(withSub.contains('sub') ? 'ACCEPTED libass loaded the ASS' : 'REJECTED no sub track');

    // --- the toggle the CC button and the C key drive ----------------------
    await engine.setSubtitle(null);
    await _wait(1000);
    check('sub off');
    started = DateTime.now();
    await engine.setSubtitle(_sampleAss);
    _say('re-attach took ${DateTime.now().difference(started).inMilliseconds} ms');
    await _wait(1500);
    check('sub on again');

    // --- 3. survive the reopen a quality switch performs --------------------
    _say('reopening with retainSubtitle: true — what switchQuality does');
    await engine.open(variant, retainSubtitle: true);
    await _wait(3000);
    check('reopen');
    final after = await _mpvTracks(engine);
    _say('tracks after reopen: $after');
    _say('engine.subtitle still set: ${engine.subtitle != null}');
    _say(after.contains('sub') ? 'SURVIVED reattached after the reopen' : 'LOST captions dropped');

    // The control. Without it, "survived" proves nothing about `retainSubtitle`
    // — it would read the same if a reopen never dropped the track at all.
    await engine.open(variant);
    await _wait(3000);
    final control = await _mpvTracks(engine);
    _say('CONTROL reopen without the flag: $control — '
        '${control.contains('sub') ? 'STILL THERE, so retainSubtitle proves nothing' : 'dropped, as expected'}');

    _say('done');
  } on Object catch (error, stack) {
    _say('FAILED $error\n$stack');
    exit(1);
  }
  exit(0);
}

Future<void> _probe(ProviderContainer container) async {
  final engine = container.read(playbackEngineProvider);
  final captions = container.read(captionsProvider.notifier);

  int? textureId() => engine is MediaKitEngine ? engine.videoController.id.value : null;

  try {
    _say('waiting for playback');
    final deadline = DateTime.now().add(const Duration(seconds: 60));
    while (engine.position <= Duration.zero ||
        engine.duration <= Duration.zero ||
        container.read(playbackProvider).source == null) {
      // **Report the reason, not just the timeout.** `PlaybackController` puts
      // the ladder's verdict in state and nothing writes it to stderr, so a
      // probe that only says "nothing played" hides an F20 refusal behind what
      // reads like a probe bug — which cost a measurement run before this line
      // existed.
      final failure = container.read(playbackProvider);
      if (failure.error != null) {
        _say('FAILED playback error ${failure.errorCode}: ${failure.error} '
            '(retry: ${failure.errorRetry?.name})');
        exit(1);
      }
      if (DateTime.now().isAfter(deadline)) {
        _say('FAILED nothing started playing within 60 s '
            '(source=${failure.source != null} loading=${failure.isLoading})');
        exit(1);
      }
      await _wait(250);
    }

    // Same trap as `controls_probe`: media_kit frees and recreates the texture
    // ~1 s after an open, once the video's real size is known. A baseline read
    // before that settle reports every later comparison as a rebuild.
    await _wait(3000);
    var last = textureId();
    _say('texture id at rest: $last');
    _say('mpv tracks before captions: ${await _mpvTracks(engine)}');

    void checkTexture(String label) {
      final now = textureId();
      _say('$label: texture=$now ${now == last ? 'UNCHANGED' : 'REBUILT'} '
          'pos=${engine.position} playing=${engine.playing}');
      last = now;
    }

    // --- the track list ----------------------------------------------------
    final tracksDeadline = DateTime.now().add(const Duration(seconds: 20));
    while (container.read(captionsProvider).isLoadingTracks &&
        DateTime.now().isBefore(tracksDeadline)) {
      await _wait(250);
    }
    final list = container.read(captionsProvider).tracks;
    _say('tracks: ${list.length} '
        '[${list.map((t) => '${t.id}/${t.languageCode}${t.isAutoGenerated ? ':asr' : ''}').join(', ')}]');
    if (list.isEmpty) {
      _say('no caption tracks on this video — pick another with RILL_OPEN_VIDEO');
      _say('done');
      exit(0);
    }

    // --- 1. attaching must not rebuild the output --------------------------
    //
    // The whole stop condition, in one comparison. Timed too, because "free" is
    // a claim about wall clock as much as about the texture.
    final positionBefore = engine.position;
    var started = DateTime.now();
    await captions.select(list.first.id);
    final attachMs = DateTime.now().difference(started).inMilliseconds;
    await _wait(1500);
    checkTexture('captions on (${list.first.id})');
    _say('attach took $attachMs ms; position went '
        '${positionBefore.inSeconds}s -> ${engine.position.inSeconds}s');
    _say('mpv tracks with captions: ${await _mpvTracks(engine)}');

    // --- 3. did libass accept the document? --------------------------------
    //
    // A `sub:ass` entry in mpv's own track list is the evidence. If `ass.ts`
    // emitted something libass rejected, the track would be absent or the codec
    // would not be `ass`, and the picture would look identical either way.
    final withSubs = await _mpvTracks(engine);
    _say(withSubs.contains('sub') ? 'ACCEPTED libass loaded the track' : 'REJECTED no sub track');

    // --- switching language, also free? ------------------------------------
    if (list.length > 1) {
      started = DateTime.now();
      await captions.select(list[1].id);
      final switchMs = DateTime.now().difference(started).inMilliseconds;
      await _wait(1500);
      checkTexture('language -> ${list[1].id}');
      _say('language switch took $switchMs ms');
      await captions.select(list.first.id);
      await _wait(1000);
    }

    // --- toggling off and on -----------------------------------------------
    await captions.select(null);
    await _wait(1000);
    checkTexture('captions off');
    await captions.select(list.first.id);
    await _wait(1500);
    checkTexture('captions on again');

    // --- 2. survive a quality switch ---------------------------------------
    //
    // The switch reopens the media, which is exactly why this needs measuring
    // rather than assuming: mpv drops external subtitle tracks on a reopen, and
    // `retainSubtitle` is what puts them back.
    final variants = distinctQualities(container.read(playbackProvider).source?.variants ?? const []);
    final open = container.read(playbackProvider).variant;
    final target = variants.firstWhere(
      (v) => v.height != open?.height,
      orElse: () => variants.first,
    );
    _say('switching quality ${open?.height}p -> ${target.height}p with captions on');
    final before = engine.position;
    started = DateTime.now();
    await container.read(playbackProvider.notifier).switchQuality(target);
    final resumeDeadline = started.add(const Duration(seconds: 30));
    while (engine.position <= before && DateTime.now().isBefore(resumeDeadline)) {
      await _wait(50);
    }
    await _wait(2000);
    _say('after switch: mpv reports ${engine.height}p, '
        'resumed in ${DateTime.now().difference(started).inMilliseconds} ms, '
        'texture=${textureId()}');
    _say('engine.subtitle still attached: ${engine.subtitle != null}');
    final afterSwitch = await _mpvTracks(engine);
    _say('mpv tracks after switch: $afterSwitch');
    _say(afterSwitch.contains('sub') ? 'SURVIVED captions are still loaded' : 'LOST captions dropped');

    _say('done');
  } on Object catch (error, stack) {
    _say('FAILED $error\n$stack');
    exit(1);
  }
  exit(0);
}
