/**
 * json3 on disk -> ASS, offline.
 *
 * `YT_DUMP_ASS` on `probe-playback.ts` needs the network and a live track; this
 * runs the same `convert()` against a saved document, which is what makes a
 * styling change reviewable without re-fetching a caption track every time.
 *
 *   bun run scratch/dump-ass.ts <doc.json> <out.ass> [asr]
 */
import * as fs from 'fs';
import { convert } from '../src/captions/service.ts';

const [input, output, kind] = process.argv.slice(2);
if (input === undefined || output === undefined) {
  throw new Error('usage: dump-ass.ts <doc.json> <out.ass> [asr]');
}

const isAutoGenerated = kind === 'asr';
const content = convert(fs.readFileSync(input, 'utf8'), {
  baseUrl: 'https://example.invalid/timedtext',
  track: {
    id: isAutoGenerated ? 'a.en' : '.en',
    languageCode: 'en',
    label: 'English',
    isAutoGenerated,
    isTranslatable: false,
  },
});

fs.writeFileSync(output, content.content);
console.error(`${input} -> ${output}: ${content.cueCount} cue(s)`);
