import { createSession } from '../src/innertube/session.ts';
import { listCaptionTracks } from '../src/captions/service.ts';
import { parseJson3 } from '../src/captions/json3.ts';

async function main() {
  const session = await createSession({ clientType: 'MWEB' });
  const queries = ['TED talks', 'music video', 'vlog', 'gaming', 'news', 'tutorial'];
  const videoIds = new Set<string>();
  
  function findVideoIds(obj: any) {
    if (!obj) return;
    if (typeof obj === 'object') {
      if (Array.isArray(obj)) {
        for (const item of obj) findVideoIds(item);
      } else {
        if (typeof obj.videoId === 'string' && obj.videoId.length === 11) {
          videoIds.add(obj.videoId);
        }
        for (const key of Object.keys(obj)) {
          findVideoIds(obj[key]);
        }
      }
    }
  }

  for (const q of queries) {
    const feed = await session.execute('/search', { query: q });
    findVideoIds(feed);
  }
  
  const ids = Array.from(videoIds).slice(0, 5);
  console.log('Found ' + ids.length + ' videos.');

  let totalTracks = 0;
  let draggableManual = 0;
  let anchoredManual = 0;
  let draggableAsr = 0;
  let anchoredAsr = 0;
  
  const extraIds = ['L-BgxLtMxh0', '1S7uIQmkRzk', '8Oos6D4_Bjo'];
  for (const extra of extraIds) {
    if (!ids.includes(extra)) ids.push(extra);
  }

  for (const videoId of ids) {
    try {
      const p = listCaptionTracks(session, videoId);
      const timeout = new Promise<any>((_, r) => setTimeout(() => r(new Error('timeout')), 2000));
      const { sources } = await Promise.race([p, timeout]);
      for (const source of sources) {
        totalTracks++;
        const isAsr = source.track.isAutoGenerated;

        const url = new URL(source.baseUrl);
        url.searchParams.set('fmt', 'json3');
        const raw = await (await fetch(url.toString())).text();
        const doc = JSON.parse(raw);

        const cues = parseJson3(doc);
        const anchors = new Set<string>();
        for (const cue of cues) {
          let h = cue.style?.windowHorizontalPercent ?? null;
          let v = cue.style?.windowVerticalPercent ?? null;
          anchors.add(h + ',' + v);
        }

        const isDraggable = anchors.size <= 1;

        if (isAsr) {
          if (isDraggable) draggableAsr++;
          else anchoredAsr++;
        } else {
          if (isDraggable) draggableManual++;
          else anchoredManual++;
        }
        
        if (extraIds.includes(videoId)) {
           console.log('Demo ' + videoId + ' - Asr:' + isAsr + ' - Draggable:' + isDraggable + ' - Anchors:' + anchors.size);
        }
      }
    } catch (e: any) {
      console.error('Error on video ' + videoId + ': ' + e.message);
    }
  }

  console.log('\n--- Results ---');
  console.log('Total tracks: ' + totalTracks);
  console.log('Manual tracks: ' + (draggableManual + anchoredManual));
  console.log('  Draggable (<=1 anchor): ' + draggableManual);
  console.log('  Authored (>1 anchors):  ' + anchoredManual);
  console.log('ASR tracks: ' + (draggableAsr + anchoredAsr));
  console.log('  Draggable (<=1 anchor): ' + draggableAsr);
  console.log('  Authored (>1 anchors):  ' + anchoredAsr);
}

main().catch(console.error);
