import { createSession } from '../src/innertube/session.ts';
import { listCaptionTracks } from '../src/captions/service.ts';
import { parseJson3 } from '../src/captions/json3.ts';

async function main() {
  const session = await createSession({ clientType: 'MWEB' });
  const ids = ['L-BgxLtMxh0'];

  for (const videoId of ids) {
    const p = listCaptionTracks(session, videoId);
    const { sources } = await p;
    for (const source of sources) {
      if (source.track.isAutoGenerated) continue;
      const url = new URL(source.baseUrl);
      url.searchParams.set('fmt', 'json3');
      const raw = await (await fetch(url.toString())).text();
      const cues = parseJson3(JSON.parse(raw));
      
      const anchors = new Set<string>();
      for (const cue of cues) {
        let h = cue.style?.positionX ?? null;
        let v = cue.style?.positionY ?? null;
        anchors.add(h + ',' + v);
      }
      console.log('Anchors:', Array.from(anchors));
    }
  }
}
main().catch(console.error);
