/**
 * Task 19, question 3: is the 3 MB caption document an outlier or a category,
 * and does a cue cache actually remove the cost of a style change on one?
 *
 * A style change re-runs `convert()` today: JSON.parse → parseJson3 → normalize
 * → group → renderAss. If the parse half dominates, caching *parsed cues* (§6
 * of the brief) is the fast path and the pathological document stops mattering.
 * If the render half dominates, the cache buys nothing and a style slider on
 * that track is genuinely slow.
 *
 *   bun run scratch/measure-regen.ts scratch/out/*.json
 */
import * as fs from 'fs';
import { parseJson3 } from '../src/captions/json3.ts';
import { groupAsrCues, normalizeCues, type Cue } from '../src/captions/cues.ts';
import { renderAss } from '../src/captions/ass.ts';

const REPEATS = 20;

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)]!;
}

function time(repeats: number, fn: () => void): number {
  fn(); // warm
  const samples: number[] = [];
  for (let i = 0; i < repeats; i++) {
    const started = performance.now();
    fn();
    samples.push(performance.now() - started);
  }
  return median(samples);
}

const rows: string[][] = [
  ['document', 'bytes', 'cues', 'segs', 'JSON.parse', 'to cues', 'renderAss', 'full', 'cached'],
];

for (const path of process.argv.slice(2)) {
  const body = fs.readFileSync(path, 'utf8');
  const name = path.split(/[\\/]/).pop()!;
  const asr = /a\.|asr/.test(name);

  const toCues = (raw: unknown): Cue[] => {
    const normalized = normalizeCues(parseJson3(raw));
    return asr ? groupAsrCues(normalized) : normalized;
  };

  const parsed = JSON.parse(body) as unknown;
  const cues = toCues(parsed);
  const segs = cues.reduce((total, cue) => total + cue.segments.length, 0);

  const jsonMs = time(REPEATS, () => void JSON.parse(body));
  const cuesMs = time(REPEATS, () => void toCues(JSON.parse(body))) - jsonMs;
  const renderMs = time(REPEATS, () =>
    void renderAss({ cues, isAutoGenerated: asr, languageCode: 'en' }),
  );

  rows.push([
    name.replace(/\.json$/, ''),
    `${(body.length / 1024).toFixed(0)} KB`,
    String(cues.length),
    String(segs),
    `${jsonMs.toFixed(1)} ms`,
    `${cuesMs.toFixed(1)} ms`,
    `${renderMs.toFixed(1)} ms`,
    `${(jsonMs + cuesMs + renderMs).toFixed(1)} ms`,
    `${renderMs.toFixed(1)} ms`,
  ]);
}

const widths = rows[0]!.map((_, i) => Math.max(...rows.map((row) => row[i]!.length)));
for (const row of rows) {
  console.error(row.map((cell, i) => cell.padEnd(widths[i]!)).join('  '));
}
