import { createSession } from '../src/innertube/session.ts';
import { listCaptionTracks } from '../src/captions/service.ts';
import { parseJson3 } from '../src/captions/json3.ts';

async function main() {
  console.log('Creating session...');
  const session = await createSession({ clientType: 'MWEB' });
  console.log('Fetching feed...');
  const feed = await session.execute('/search', { query: 'TED talks' });
  
  const videoIds = new Set<string>();
  
  function findVideoIds(obj: any) {
    if (!obj) return;
    if (typeof obj === 'object') {
      if (Array.isArray(obj)) {
        for (const item of obj) findVideoIds(item);
      } else {
        if (typeof obj.videoId === 'string' && obj.videoId.length === 11) {
          videoIds.add(obj.videoId);
        }
        for (const key of Object.keys(obj)) {
          findVideoIds(obj[key]);
        }
      }
    }
  }
  
  findVideoIds(feed);
  const ids = Array.from(videoIds).slice(0, 40);
  console.log(`Found ${ids.length} videos.`);

  let totalTracks = 0;
  let styledManual = 0;
  let plainManual = 0;
  let styledAsr = 0;
  let plainAsr = 0;

  for (const videoId of ids) {
    try {
      const p = listCaptionTracks(session, videoId);
      const timeout = new Promise<any>((_, r) => setTimeout(() => r(new Error('timeout')), 2000));
      const { sources } = await Promise.race([p, timeout]);
      for (const source of sources) {
        totalTracks++;
        const isAsr = source.track.isAutoGenerated;

        const url = new URL(source.baseUrl);
        url.searchParams.set('fmt', 'json3');
        const raw = await (await fetch(url.toString())).text();
        const doc = JSON.parse(raw);

        // Run it through the actual parser
        const cues = parseJson3(doc);
        
        // The predicate we would actually use
        const isStyled = cues.some(cue => cue.style !== null || cue.segments.some(seg => seg.style !== null));

        if (isAsr) {
          if (isStyled) styledAsr++;
          else plainAsr++;
        } else {
          if (isStyled) styledManual++;
          else plainManual++;
        }
      }
    } catch (e: any) {
      console.error(`Error on video ${videoId}:`, e.message);
    }
  }

  console.log('\n--- Results ---');
  console.log(`Total tracks: ${totalTracks}`);
  console.log(`Manual tracks: ${styledManual + plainManual}`);
  console.log(`  Styled: ${styledManual}`);
  console.log(`  Plain:  ${plainManual}`);
  console.log(`ASR tracks: ${styledAsr + plainAsr}`);
  console.log(`  Styled: ${styledAsr}`);
  console.log(`  Plain:  ${plainAsr}`);
  
  const totalStyled = styledManual + styledAsr;
  const fraction = totalTracks > 0 ? (totalStyled / totalTracks) : 0;
  console.log(`Fraction of tracks classified as styled: ${totalStyled} / ${totalTracks} (${(fraction * 100).toFixed(1)}%)`);
}

main().catch(console.error);
