/**
 * Fetch the *auto-generated* caption track for a video and save raw json3 + ASS.
 * Throwaway measurement helper for the Task 19 cadence probe.
 *
 *   bun run scratch/probe-asr-fetch.ts <videoId>
 */
import * as fs from 'fs';
import { createSession } from '../src/innertube/session.ts';
import { listCaptionTracks, getCaptionTrack } from '../src/captions/service.ts';

const videoId = process.argv[2];
if (videoId === undefined) throw new Error('usage: probe-asr-fetch.ts <videoId>');

const session = await createSession({ clientType: 'MWEB' });
const { sources } = await listCaptionTracks(session, videoId);
console.error(`${videoId}: ${sources.length} track(s)`);
for (const s of sources) {
  console.error(`  ${s.track.id} asr=${s.track.isAutoGenerated} lang=${s.track.languageCode}`);
}
const asr = sources.find((s) => s.track.isAutoGenerated) ?? sources[0];
if (asr === undefined) throw new Error('no tracks');

const url = new URL(asr.baseUrl);
url.searchParams.set('fmt', 'json3');
const raw = await (await fetch(url)).text();
fs.writeFileSync(`scratch/out/${videoId}-asr.json`, raw);

const track = await getCaptionTrack(session, videoId, asr.track.id);
fs.writeFileSync(`scratch/out/${videoId}-asr.ass`, track.content);
console.error(`  -> ${track.cueCount} cue(s), ${track.content.length} bytes`);
