/**
 * Task 19: does the layered caption actually composite?
 *
 * Three claims, none of which can be read off the format spec, all of which
 * `ass.ts` now depends on:
 *
 *  1. A `BorderStyle: 3` event with `\1a&HFF&` draws its **box** while drawing no
 *     glyphs — the trick that lets the text event keep its outline.
 *  2. A `BorderStyle: 4` event draws a rectangle round the whole block from
 *     `\4c`, and `\3a&HFF&` suppresses its per-line box so the two backdrops do
 *     not double up.
 *  3. Layers stack in the order the numbers say, with the text on top.
 *
 * Renders through the *bundled* libmpv (hard invariant 8) and prints, for each
 * band, how much of it is background-coloured and how much is text-coloured — so
 * "the box is there" and "the glyphs are there" are separate answers.
 *
 *   bun run scratch/probe-layers.ts [outdir]
 */
import { dlopen, FFIType, ptr, toArrayBuffer } from 'bun:ffi';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { renderAss } from '../src/captions/ass.ts';
import type { Cue } from '../src/captions/cues.ts';

const DLL = 'C:/Projects/NativeYouTube/app/build/windows/x64/runner/Release/libmpv-2.dll';
const WIDTH = 1920;
const HEIGHT = 1080;

const cue = (startMs: number, text: string, style: Cue['style']): Cue => ({
  startMs,
  endMs: startMs + 900,
  segments: [{ text, offsetMs: null, style: null }],
  style,
});

const WHITE = { r: 255, g: 255, b: 255, a: 1 };
const RED = { r: 255, g: 0, b: 0, a: 1 };

const emptyStyle = {
  alignment: null,
  positionX: null,
  positionY: null,
  textColor: null,
  backgroundColor: null,
  edgeColor: null,
  edgeStyles: null,
  fontFamily: null,
  fontSizePercent: null,
  bold: null,
  italic: null,
  underline: null,
};

/** Three cues at three moments, so one render answers all three questions. */
const cues: Cue[] = [
  cue(0, 'boxed and outlined' + String.fromCharCode(10) + 'on two lines', {
    ...emptyStyle,
    edgeStyles: ['outline'],
  }),
  cue(1000, 'window as well', { ...emptyStyle, edgeStyles: ['outline'] }),
  cue(2000, 'neither', { ...emptyStyle, edgeStyles: ['outline'] }),
];

const cases = [
  { label: 'default (box, no window)', style: null, want: 'box + outline' },
  {
    label: 'box + window',
    style: {
      fontFamily: null,
      fontSizePercent: null,
      textColor: null,
      background: { r: 0, g: 0, b: 0, a: 0.75 },
      window: { r: 255, g: 0, b: 0, a: 0.6 },
      edgeStyle: null,
    },
    want: 'window rectangle wider than the box',
  },
  {
    label: 'background off',
    style: {
      fontFamily: null,
      fontSizePercent: null,
      textColor: null,
      background: { r: 0, g: 0, b: 0, a: 0 },
      window: null,
      edgeStyle: null,
    },
    want: 'outline only, no box, task 17 bytes',
  },
] as const;

const lib = dlopen(DLL, {
  mpv_create: { args: [], returns: FFIType.ptr },
  mpv_initialize: { args: [FFIType.ptr], returns: FFIType.int },
  mpv_set_option_string: { args: [FFIType.ptr, FFIType.ptr, FFIType.ptr], returns: FFIType.int },
  mpv_command_string: { args: [FFIType.ptr, FFIType.ptr], returns: FFIType.int },
  mpv_wait_event: { args: [FFIType.ptr, FFIType.double], returns: FFIType.ptr },
  mpv_terminate_destroy: { args: [FFIType.ptr], returns: FFIType.void },
});

const BS = String.fromCharCode(92);
const fwd = (value: string) => value.split(BS).join('/');
const keep = process.argv[2];

for (const testCase of cases) {
  const document = renderAss(
    { cues, isAutoGenerated: false, languageCode: 'en' },
    { style: testCase.style },
  );
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'rill-layer-'));
  const assPath = path.join(dir, 'm.ass');
  const rawPath = path.join(dir, 'bg.raw');
  fs.writeFileSync(assPath, document, 'utf8');
  // Mid grey, so a 75% black box and white glyphs are both obvious against it.
  fs.writeFileSync(rawPath, Buffer.alloc(WIDTH * HEIGHT * 3, 128));

  const held: Buffer[] = [];
  const cstr = (value: string) => {
    const buffer = Buffer.from(value + '\0', 'utf8');
    held.push(buffer);
    return ptr(buffer);
  };
  const h = lib.symbols.mpv_create();
  const opt = (name: string, value: string) =>
    lib.symbols.mpv_set_option_string(h, cstr(name), cstr(value));

  opt('terminal', 'yes');
  opt('msg-level', 'all=error');
  opt('vo', 'image');
  opt('vo-image-format', 'jpg');
  opt('vo-image-outdir', fwd(dir));
  opt('sub-files', fwd(assPath));
  opt('sid', '1');
  opt('sub-ass', 'yes');
  opt('sub-visibility', 'yes');
  opt('audio', 'no');
  opt('untimed', 'yes');
  opt('hwdec', 'no');
  opt('keep-open', 'no');
  opt('demuxer', 'rawvideo');
  opt('demuxer-rawvideo-w', String(WIDTH));
  opt('demuxer-rawvideo-h', String(HEIGHT));
  opt('demuxer-rawvideo-mp-format', 'bgr24');
  // Three frames, one per cue, half a second into each.
  opt('demuxer-rawvideo-fps', '1');

  lib.symbols.mpv_initialize(h);
  // One frame is enough per case: the first cue is on screen at t=0, and the
  // three cases differ in the document, not in the moment.
  lib.symbols.mpv_command_string(h, cstr(`loadfile "${fwd(rawPath)}"`));
  const started = Date.now();
  while (Date.now() - started < 30_000) {
    const event = lib.symbols.mpv_wait_event(h, 0.5);
    if (!event) continue;
    const id = new DataView(toArrayBuffer(event, 0, 8)).getInt32(0, true);
    if (id === 7 || id === 1) break;
  }
  lib.symbols.mpv_terminate_destroy(h);

  const frame = fs.readdirSync(dir).find((name) => /[.]jpg$/.test(name));
  if (frame === undefined) {
    console.error(`${testCase.label}: NO FRAME`);
    continue;
  }
  const bmpPath = path.join(dir, 'frame.bmp');
  Bun.spawnSync([
    'powershell',
    '-NoProfile',
    '-Command',
    `Add-Type -AssemblyName System.Drawing; $i = [System.Drawing.Image]::FromFile(` +
      `'${path.join(dir, frame)}'); $i.Save('${bmpPath}', ` +
      `[System.Drawing.Imaging.ImageFormat]::Bmp); $i.Dispose()`,
  ]);
  const bmp = fs.readFileSync(bmpPath);
  const offset = bmp.readUInt32LE(10);
  const stride = Math.ceil((bmp.readInt32LE(18) * (bmp.readUInt16LE(28) / 8)) / 4) * 4;
  const bpp = bmp.readUInt16LE(28) / 8;

  let dark = 0;
  let bright = 0;
  let reddish = 0;
  let minX = WIDTH;
  let maxX = 0;
  let minY = HEIGHT;
  let maxY = 0;
  for (let y = 900; y < HEIGHT; y++) {
    const base = offset + (HEIGHT - 1 - y) * stride;
    for (let x = 0; x < WIDTH; x++) {
      const b = bmp[base + x * bpp]!;
      const g = bmp[base + x * bpp + 1]!;
      const r = bmp[base + x * bpp + 2]!;
      const grey = Math.abs(r - 128) < 12 && Math.abs(g - 128) < 12 && Math.abs(b - 128) < 12;
      if (grey) continue;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
      if (r > 200 && g > 200 && b > 200) bright++;
      else if (r > g + 40 && r > b + 40) reddish++;
      else if (r < 100 && g < 100 && b < 100) dark++;
    }
  }
  console.error(
    `${testCase.label.padEnd(24)} glyphs=${String(bright).padStart(6)} ` +
      `box=${String(dark).padStart(6)} window=${String(reddish).padStart(6)}  ` +
      `ink ${maxX - minX + 1}x${maxY - minY + 1}  (want: ${testCase.want})`,
  );
  if (keep !== undefined) {
    fs.mkdirSync(keep, { recursive: true });
    fs.copyFileSync(
      path.join(dir, frame),
      path.join(keep, `${testCase.label.replace(/[^a-z]+/gi, '-')}.jpg`),
    );
    fs.writeFileSync(
      path.join(keep, `${testCase.label.replace(/[^a-z]+/gi, '-')}.ass`),
      document,
    );
  }
  fs.rmSync(dir, { recursive: true, force: true });
}
