/**
 * Throwaway: does forceFontFamily correctly gate the authored font, in both
 * directions, on a track that authors ONLY font+colour (matching the user's
 * exact report)?
 */
import { renderAss } from '../src/captions/ass.ts';
import type { CueTrack } from '../src/captions/cues.ts';
import type { CaptionStyle } from '../src/captions/style.ts';

const NO_STYLE = {
  alignment: null, positionX: null, positionY: null,
  fontFamily: null, fontSizePercent: null,
  textColor: null, backgroundColor: null, edgeColor: null, edgeStyles: null,
  bold: null, italic: null, underline: null,
};

// A cue authoring ONLY font + colour, matching "the styled track only
// specified font and color" from the report.
const track: CueTrack = {
  languageCode: 'en',
  isAutoGenerated: false,
  cues: [
    {
      startMs: 0, endMs: 2000,
      style: { ...NO_STYLE, fontFamily: 'Comic Sans MS', textColor: { r: 0, g: 255, b: 0, a: 1 } },
      segments: [{ text: 'hello world', offsetMs: null, style: null }],
    },
  ],
};

function textLine(ass: string): string {
  return ass.split('\n').find((l) => l.startsWith('Dialogue:') && l.includes(',Default,'))!;
}
function styleLine(ass: string): string {
  return ass.split('\n').find((l) => l.startsWith('Style: Default,'))!;
}

const base: CaptionStyle = {
  forceStyleEnabled: true,
  fontFamily: 'Georgia', forceFontFamily: true,
  fontSizePercent: null, forceFontSize: true,
  textColor: { r: 0, g: 0, b: 255 } as never, forceTextColor: true,
  textOpacity: null, forceTextOpacity: true,
  background: null, forceBackgroundColor: true,
  backgroundOpacity: null, forceBackgroundOpacity: true,
  window: null, forceWindowColor: true,
  windowOpacity: null, forceWindowOpacity: true,
  edgeStyle: null, forceEdgeStyle: true,
};

console.error('--- A: user picks Georgia + blue, force ON (master + font tile) ---');
let ass = renderAss(track, { style: base });
console.error('Style line:', styleLine(ass));
console.error('Text line: ', textLine(ass));

console.error('\n--- B: same, master OFF (forceStyleEnabled: false) ---');
ass = renderAss(track, { style: { ...base, forceStyleEnabled: false } });
console.error('Style line:', styleLine(ass));
console.error('Text line: ', textLine(ass));

console.error('\n--- C: master ON, just the font tile OFF (forceFontFamily: false) ---');
ass = renderAss(track, { style: { ...base, forceFontFamily: false } });
console.error('Style line:', styleLine(ass));
console.error('Text line: ', textLine(ass));
