/**
 * The caption track list, out of a `/player` response.
 *
 * No extra request to YouTube: the tracks ride on the `/player` response
 * `playback.open` and `video.info` already fetch and cache
 * (`innertube/player-response.ts`), so a video's caption list costs nothing on
 * top of opening it.
 *
 * Two things about the shape are measured rather than assumed (2026-08-18):
 *
 *  - **`baseUrl` is absolute from `VISIONOS` and relative from `WEB`/`MWEB`.**
 *    Both forms occur, so both are resolved against `https://www.youtube.com`
 *    here rather than at the fetch site.
 *  - **`translationLanguages` is not a list of missing tracks.** One real track
 *    can arrive beside ~156 of them; they are machine translations of that track,
 *    reachable by appending `&tlang=`, and they are out of scope. A track list far
 *    shorter than youtube.com's picker is expected and correct.
 *
 * The URL never crosses the RPC boundary. It is signed — `sparams`/`signature` —
 * and the sidecar is what fetches it, so `CaptionTrack` carries an opaque `id`
 * and the URL stays here. That is the same reasoning as hard invariant 2, applied
 * to a different endpoint: nothing outside this process should be able to hold a
 * URL whose signing it does not own.
 */

import { logger } from '../log.ts';
import type { CaptionTrack } from '../types.ts';
import { text } from './text.ts';
import { asArray, get, isObject, str, type Json } from './tree.ts';

const log = logger('captions');

/** A track plus the address the sidecar fetches it from. Never leaves the sidecar. */
export interface CaptionTrackSource {
  track: CaptionTrack;
  /** Absolute, signed, ready to fetch. `fmt` is appended by the fetcher. */
  baseUrl: string;
}

const YOUTUBE_ORIGIN = 'https://www.youtube.com';

function absolute(baseUrl: string): string | null {
  try {
    return new URL(baseUrl, YOUTUBE_ORIGIN).toString();
  } catch {
    return null;
  }
}

/**
 * A display label for the track, from whichever field carries one.
 *
 * `name` is a text runs object on some responses and a `simpleText` on others.
 * Falls back to the language code rather than dropping the track: an unlabelled
 * track is still a track the user can pick, and "en" beats absence.
 */
function label(entry: Record<string, unknown>, languageCode: string): string {
  // `text()` handles both, and it is the same helper every other parser uses —
  // hand-rolling a `runs[0].text` walk here would miss the multi-run case and
  // would have to be kept in step with the shared one by hand.
  return text(entry['name']) ?? text(entry['languageName']) ?? languageCode;
}

/**
 * Every caption track on this `/player` response, in YouTube's own order.
 *
 * Never throws (hard invariant 4). A response with no `captions` node returns an
 * empty array, which is an ordinary answer — measured 2026-08-18, 10 of 42
 * playable videos in a real feed sample carry no captions at all.
 */
export function parseCaptionTracks(raw: unknown): CaptionTrackSource[] {
  const body = isObject(raw) && isObject(raw['data']) ? (raw['data'] as Json) : (raw as Json);
  const list = asArray(
    get(body, 'captions', 'playerCaptionsTracklistRenderer', 'captionTracks') ??
      get(body, 'captions', 'captionTracks'),
  );

  const sources: CaptionTrackSource[] = [];
  for (const entry of list) {
    if (!isObject(entry)) continue;

    const baseUrl = str(entry['baseUrl']);
    const languageCode = str(entry['languageCode']);
    if (baseUrl === null || languageCode === null) {
      log.warn('caption track without baseUrl or languageCode — skipped');
      continue;
    }
    const url = absolute(baseUrl);
    if (url === null) {
      log.warn(`caption track with unparseable baseUrl — skipped (${languageCode})`);
      continue;
    }

    const isAutoGenerated = str(entry['kind']) === 'asr';
    sources.push({
      baseUrl: url,
      track: {
        // `vssId` is YouTube's own stable key and distinguishes the manual and
        // auto-generated tracks of the same language — ".en" against "a.en" —
        // which a language code alone cannot. Synthesised when absent so the id
        // is never null and the client can always address a track.
        id: str(entry['vssId']) ?? `${isAutoGenerated ? 'a.' : '.'}${languageCode}`,
        languageCode,
        label: label(entry, languageCode),
        isAutoGenerated,
        isTranslatable: entry['isTranslatable'] === true,
      },
    });
  }

  return sources;
}
