/**
 * `parsePlayer` — raw `/player` response → formats, storyboards, cpn.
 *
 * Hard invariant 2 lives here in the negative: this module never produces a
 * `SignedUrl`. It reports what YouTube sent as `rawUrl` / `signatureCipher`, and
 * the decipher path — not the parser — is the only thing allowed to mint a URL
 * fit to cross the RPC boundary. An unsigned `n` throttles to ~50 KB/s and looks
 * exactly like a bad connection, so the type system has to be the thing that
 * stops it, not a code review.
 */

import type { PlayerFormat, PlayerResult, Storyboard } from '../types.ts';
import { asArray, deepFind, get, isObject, num, str, type Json } from './tree.ts';

/** `video/mp4; codecs="avc1.640028"` → `{ mime: 'video/mp4', codecs: 'avc1.640028' }`. */
function splitMimeType(value: string | null): { mime: string | null; codecs: string | null } {
  if (!value) return { mime: null, codecs: null };
  const [mime = null, ...rest] = value.split(';');
  const codecMatch = /codecs="([^"]+)"/.exec(rest.join(';'));
  return { mime: mime?.trim() ?? null, codecs: codecMatch?.[1] ?? null };
}

function mapFormat(entry: Json, isAdaptive: boolean): PlayerFormat | null {
  if (!isObject(entry)) return null;
  const itag = num(entry['itag']);
  if (itag === null) return null;

  const { mime, codecs } = splitMimeType(str(entry['mimeType']) ?? str(entry['mime_type']));
  const hasVideo = num(entry['width']) !== null || /^video\//.test(mime ?? '');
  const hasAudio =
    str(entry['audioQuality']) !== null ||
    num(entry['audioSampleRate']) !== null ||
    /^audio\//.test(mime ?? '');

  return {
    itag,
    mimeType: mime,
    codecs,
    bitrate: num(entry['bitrate']),
    width: num(entry['width']),
    height: num(entry['height']),
    fps: num(entry['fps']),
    audioQuality: str(entry['audioQuality']),
    audioSampleRate: num(entry['audioSampleRate']),
    contentLength: num(entry['contentLength']),
    approxDurationMs: num(entry['approxDurationMs']),
    hasVideo,
    hasAudio,
    isAdaptive,
    rawUrl: str(entry['url']),
    signatureCipher: str(entry['signatureCipher']) ?? str(entry['cipher']),
  };
}

/**
 * Storyboard specs are a pipe-delimited string, not JSON:
 *
 *   <baseUrl>|w#h#count#cols#rows#intervalMs#name#sigh|w#h#…
 *
 * Each trailing segment is one zoom level. `$L` in the base URL is the level
 * index and `$N` the level's name field; both stay in the template so the UI can
 * pick a level per hover. Per F8 these sprite sheets are the only hover-preview
 * media YouTube serves — there is no preview video in the feed.
 */
function parseStoryboardSpec(spec: string): Storyboard[] {
  const [baseUrl, ...levels] = spec.split('|');
  if (!baseUrl || levels.length === 0) return [];

  const boards: Storyboard[] = [];
  levels.forEach((level, index) => {
    const parts = level.split('#');
    const [width, height, count, columns, rows, interval, name, sigh] = parts;
    if (!width) return;

    const templateUrl = baseUrl
      .replace('$L', String(index))
      .replace('$N', name ?? 'M$M')
      .concat(sigh ? `&sigh=${sigh}` : '');

    boards.push({
      templateUrl,
      thumbnailWidth: num(width),
      thumbnailHeight: num(height),
      thumbnailCount: num(count),
      columns: num(columns),
      rows: num(rows),
      intervalMs: num(interval),
    });
  });
  return boards;
}

function extractStoryboards(body: Json): Storyboard[] {
  const spec =
    str(get(body, 'storyboards', 'playerStoryboardSpecRenderer', 'spec')) ??
    str(get(body, 'storyboards', 'playerLiveStoryboardSpecRenderer', 'spec'));
  if (spec) return parseStoryboardSpec(spec);

  // Layout moved: find any node carrying a spec-looking string.
  const holder = deepFind(body, (node) => {
    const value = node['spec'];
    return typeof value === 'string' && value.includes('|') && value.startsWith('http');
  });
  const fallback = holder ? str(holder['spec']) : null;
  return fallback ? parseStoryboardSpec(fallback) : [];
}

/**
 * The client playback nonce.
 *
 * A raw `/player` response does not contain one — the CPN is generated by the
 * client and only appears once youtubei.js has attached it, or echoed back in
 * the playback-tracking URLs. We read it where it exists and return `null`
 * otherwise; `playback.report` supplies its own rather than inventing one here.
 */
function extractCpn(body: Json): string | null {
  const direct = str(get(body, 'cpn'));
  if (direct) return direct;

  const trackingUrl = str(get(body, 'playbackTracking', 'videostatsPlaybackUrl', 'baseUrl'));
  const match = trackingUrl ? /[?&]cpn=([\w-]+)/.exec(trackingUrl) : null;
  return match?.[1] ?? null;
}

export function parsePlayer(raw: Json): PlayerResult {
  const body = isObject(raw) && isObject(raw['data']) ? (raw['data'] as Json) : raw;

  const streaming = get(body, 'streamingData') ?? get(body, 'streaming_data');
  const progressive = asArray(get(streaming, 'formats'))
    .map((entry) => mapFormat(entry, false))
    .filter((format): format is PlayerFormat => format !== null);
  const adaptive = asArray(get(streaming, 'adaptiveFormats') ?? get(streaming, 'adaptive_formats'))
    .map((entry) => mapFormat(entry, true))
    .filter((format): format is PlayerFormat => format !== null);

  const formats = [...adaptive, ...progressive];
  const details = get(body, 'videoDetails');

  const lengthSeconds = num(get(details, 'lengthSeconds'));
  const isLive = get(details, 'isLive') === true || get(details, 'isLiveContent') === true;

  return {
    videoId: str(get(details, 'videoId')),
    formats,
    storyboards: extractStoryboards(body),
    cpn: extractCpn(body),
    playabilityStatus: str(get(body, 'playabilityStatus', 'status')),
    playabilityReason:
      str(get(body, 'playabilityStatus', 'reason')) ??
      str(get(body, 'playabilityStatus', 'messages', '0')),
    durationSeconds: isLive ? null : lengthSeconds,
    isLive,
    // F3: WEB is SABR-only. Measured on a real WEB response: all 40 adaptive
    // formats arrive with neither a URL nor a cipher, while itag 18 — muxed,
    // progressive, 360p — still carries a plain URL.
    //
    // So this is deliberately about the *adaptive* ladder, not about every
    // format. Defining it as "no format has a URL" would have called that
    // response non-SABR on the strength of one 360p stream, and the resolution
    // ladder would have skipped its SABR branch and quietly served 360p as if
    // it were the best available.
    sabrOnly:
      adaptive.length > 0 &&
      adaptive.every((f) => f.rawUrl === null && f.signatureCipher === null),
    serverAbrStreamingUrl:
      str(get(streaming, 'serverAbrStreamingUrl')) ?? str(get(streaming, 'server_abr_streaming_url')),
  };
}
