/// Both sides of the wire against one corpus — `protocol.md` §7.
///
/// Two languages means schema drift, and the drift is silent in one specific
/// direction: `fromJson` ignores keys it does not know, so a field added
/// sidecar-side is simply absent client-side with nothing thrown and nothing
/// logged. That is what the strict-key checks below exist for.
///
/// **The expected key set is hand-written per model, deliberately.** Deriving it
/// from the corpus makes the test unfailable — the payload would define its own
/// expectation and every unknown key would be a known one. So each set is typed
/// out from the Dart model, and the corpus is checked against *it*.
library;

import 'dart:convert';
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
import 'package:rill/domain/caption_track.dart';
import 'package:rill/domain/feed_item.dart';
import 'package:rill/domain/video_detail.dart';

/// Every key `VideoDetail` can consume. Hand-written from `lib/domain/video_detail.dart`.
///
/// Captions are **not** here, and their absence is the contract: `captions.list`
/// is a method of its own (`protocol.md` §3.8) rather than a field on this, so
/// that the caption fallback's second `/player` call stays off the video-open
/// path. If a `captions` key ever appears in this payload, the sidecar has put
/// it back and this test says so.
const videoDetailKeys = <String>{
  'id',
  'title',
  'description',
  'channelName',
  'channelId',
  'channelAvatarUrl',
  'subscriberText',
  'durationSeconds',
  'isLive',
  'viewCountText',
  'publishedText',
  'likeText',
  'isSubscribed',
  'badges',
  'premiereAtMs',
  'related',
  'relatedContinuation',
};

/// Every key `CaptionTrack` can consume. Hand-written from
/// `lib/domain/caption_track.dart`.
const captionTrackKeys = <String>{
  'id',
  'languageCode',
  'label',
  'isAutoGenerated',
  'isTranslatable',
};

/// Keys in [payload] that no field of the model claims.
///
/// Returned rather than asserted so the mutation checks can drive the same
/// function with a poisoned payload and see it fire — an auditor that cannot
/// fail converts an unchecked property into a checked-looking one.
Set<String> unknownKeys(Map<String, dynamic> payload, Set<String> expected) =>
    payload.keys.toSet().difference(expected);

/// Fields the model declares that the payload never supplies.
///
/// The other direction, and it matters as much: a key renamed sidecar-side
/// leaves the Dart field silently at its default, which for a `@Default` field
/// is indistinguishable from a real value.
Set<String> missingKeys(Map<String, dynamic> payload, Set<String> expected) =>
    expected.difference(payload.keys.toSet());

void main() {
  final corpusDir = Directory('../corpus');

  test('Contract test against exported corpus', () {
    expect(corpusDir.existsSync(), isTrue,
        reason: 'Corpus directory not found. Did you run bun run export-contract-corpus?');

    for (final entity in corpusDir.listSync()) {
      if (entity is! File || !entity.path.endsWith('.json')) continue;

      final raw = jsonDecode(entity.readAsStringSync()) as Map<String, dynamic>;

      final chips = raw['chips'] as List<dynamic>? ?? [];
      for (final chipJson in chips) {
        final chip = Chip.fromJson(chipJson as Map<String, dynamic>);
        expect(chip.label, isNotNull);
        expect(chip.token, isNotNull);
        expect(chip.scope, isNotNull);
      }

      final items = raw['items'] as List<dynamic>? ?? [];
      for (final itemJson in items) {
        final item = FeedItem.fromJson(itemJson as Map<String, dynamic>);
        // Validate that nothing threw and we have a valid FeedItem
        expect(item, isNotNull);
      }
    }
  });

  group('VideoDetail, strict-key', () {
    late Map<String, dynamic> payload;

    setUp(() {
      final file = File('../corpus/video-detail.json');
      expect(file.existsSync(), isTrue,
          reason: 'corpus/video-detail.json missing. Run bun run export-contract-corpus.');
      payload = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    });

    test('every key in the payload maps to a field', () {
      expect(unknownKeys(payload, videoDetailKeys), isEmpty,
          reason: 'the sidecar ships a key VideoDetail has no field for — it is being dropped');
    });

    test('every field the model declares is supplied', () {
      expect(missingKeys(payload, videoDetailKeys), isEmpty,
          reason: 'VideoDetail declares a field the sidecar never sends');
    });

    test('it round-trips through fromJson', () {
      final detail = VideoDetail.fromJson(payload);
      expect(detail.id, 'vid_001');
      expect(detail.title, isNotEmpty);
      expect(detail.related, isNotEmpty, reason: 'the watch page reuses MediaTile for these');
      // The nullable pair that means two different things — see the model.
      expect(detail.isLive, isFalse);
      expect(detail.premiereAtMs, isNull);
    });

    test('MUTATION: an unknown key fails, and the failure names it', () {
      final poisoned = {...payload, 'captionsWeForgotToMirror': <dynamic>[]};
      final found = unknownKeys(poisoned, videoDetailKeys);
      expect(found, {'captionsWeForgotToMirror'});
      // And `fromJson` is exactly as quiet about it as the header claims, which
      // is the whole reason the key check exists rather than a parse check.
      expect(() => VideoDetail.fromJson(poisoned), returnsNormally);
    });

    test('MUTATION: a removed key fails the other direction', () {
      final trimmed = {...payload}..remove('relatedContinuation');
      expect(missingKeys(trimmed, videoDetailKeys), {'relatedContinuation'});
    });
  });

  group('CaptionTrack, strict-key', () {
    // Inline rather than from the corpus: the fixture video carries no caption
    // tracks, so a corpus-driven check here would assert over an empty list and
    // pass against anything. This is the shape `captions.list` returns, written
    // out from `protocol.md` §3.8.
    const payload = <String, dynamic>{
      'id': 'a.en',
      'languageCode': 'en',
      'label': 'English (auto-generated)',
      'isAutoGenerated': true,
      'isTranslatable': true,
    };

    test('every key maps to a field, and every field is supplied', () {
      expect(unknownKeys(payload, captionTrackKeys), isEmpty);
      expect(missingKeys(payload, captionTrackKeys), isEmpty);
    });

    test('it round-trips', () {
      final track = CaptionTrack.fromJson(payload);
      expect(track.id, 'a.en');
      expect(track.isAutoGenerated, isTrue);
      // `id`, not `languageCode`, is the identity: a language has up to two
      // tracks and a code cannot tell `.en` from `a.en`.
      expect(track.id, isNot(track.languageCode));
    });

    test('MUTATION: an unknown key fails and names itself', () {
      expect(
        unknownKeys({...payload, 'baseUrl': 'https://…'}, captionTrackKeys),
        {'baseUrl'},
      );
    });

    test('a URL never crosses this boundary', () {
      // `baseUrl` is signed and stays sidecar-side (§3.8, and hard invariant 2's
      // reasoning on a second endpoint). If one ever appears in the DTO, the
      // check above is what catches it — this states the rule the check is for.
      expect(captionTrackKeys.any((k) => k.toLowerCase().contains('url')), isFalse);
    });
  });
}
