/**
 * The intermediate cue model — every caption format converges here before it
 * becomes ASS.
 *
 * The pipeline is `fetch → parse → cues → (group) → ASS`, and this module is the
 * waist of it. One parser exists today (`json3.ts`); the reason the waist exists
 * at all is the one that is *not* built: YTT carries per-word timing, absolute
 * positioning, colours, fonts, edge effects and karaoke, and a model shaped only
 * around "text plus a time range" would have to be replaced rather than extended
 * when that lands. So every styling field below is optional and unset by the
 * json3 parser — see `docs/architecture.md` §2.9 for what a YTT parser would
 * fill in.
 *
 * Colours are RGBA with straight alpha, in the order a human reads them. ASS
 * stores them backwards and inverted (`&HAABBGGRR`, where `AA` is *transparency*)
 * and exactly one place is allowed to know that: `ass.ts`.
 */

/**
 * ASS numpad alignment. 1–3 bottom, 4–6 middle, 7–9 top; left, centre, right.
 *
 * Named for the ASS convention rather than translated into words because it is
 * the value `\an` takes and the value libass understands, and a second
 * vocabulary in between is a second thing to get wrong.
 */
export type CueAlignment = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export interface RgbaColor {
  /** 0–255. */
  r: number;
  g: number;
  b: number;
  /** 0–1, straight alpha. 1 is opaque — the ASS inversion happens in `ass.ts`. */
  a: number;
}

/** How a caption is separated from the picture behind it. YTT names all four. */
export type CueEdgeStyle = 'none' | 'outline' | 'dropShadow' | 'raised' | 'depressed';

/**
 * Optional presentation for one cue. Every field is `null` when the source
 * format does not say — which for json3 is all of them.
 *
 * Deliberately per-cue rather than a style table: YTT positions individual cues,
 * and a table would have to be synthesised from the cues anyway. `ass.ts` emits
 * a single default `Style` and expresses everything here as inline overrides,
 * which is what libass is good at.
 */
export interface CueStyle {
  alignment: CueAlignment | null;
  /**
   * Position as a fraction of the frame, origin top-left. Both or neither —
   * `\pos` takes a pair, and half a position is not a position.
   */
  positionX: number | null;
  positionY: number | null;
  textColor: RgbaColor | null;
  backgroundColor: RgbaColor | null;
  edgeColor: RgbaColor | null;
  edgeStyle: CueEdgeStyle | null;
  fontFamily: string | null;
  /** Percentage of the player's default caption size, as YTT expresses it. */
  fontSizePercent: number | null;
  bold: boolean | null;
  italic: boolean | null;
  underline: boolean | null;
}

/**
 * One run of text within a cue.
 *
 * A manual track is one segment; an ASR track is one per word. The split is kept
 * rather than flattened because `offsetMs` is the input a karaoke renderer needs
 * (`\k`), and it is the only thing in the whole pipeline that cannot be
 * recovered afterwards. Nothing reads it today.
 */
export interface CueSegment {
  text: string;
  /** Milliseconds after the cue's own start. `null` when the format has no word timing. */
  offsetMs: number | null;
}

export interface Cue {
  startMs: number;
  /** Exclusive. Always `> startMs` by the time a cue leaves `normalizeCues`. */
  endMs: number;
  segments: CueSegment[];
  /** `null` means "the default style", not "no style". */
  style: CueStyle | null;
}

/** The whole track, as the ASS renderer receives it. */
export interface CueTrack {
  cues: Cue[];
  /** `kind: "asr"` — drives grouping, and nothing else. */
  isAutoGenerated: boolean;
  languageCode: string;
}

export function cueText(cue: Cue): string {
  return cue.segments.map((segment) => segment.text).join('');
}

// ---------------------------------------------------------------------------
// ASR grouping
// ---------------------------------------------------------------------------

/**
 * Below this a cue is a flash rather than a line, and it is merged forward.
 *
 * The value is not arbitrary: YouTube's rolling window emits a new line every
 * ~3 s but declares each one ~7 s long, so clamping to the next start produces a
 * tail of sub-second cues wherever the speaker pauses. 1200 ms is about the
 * shortest a reader can catch.
 */
const MIN_CUE_MS = 1200;

/** Two 42-character lines, the subtitling convention. Merging stops here. */
const MAX_MERGED_CHARS = 84;

/** A merged cue never outlasts this, however short its parts were. */
const MAX_MERGED_MS = 7000;

/**
 * Turn YouTube's rolling ASR window into non-overlapping readable lines.
 *
 * **Why anything is needed at all.** An ASR track is not a list of cues. It is a
 * two-row window that text scrolls through, transmitted as heavily overlapping
 * events: measured on `dQw4w9WgXcQ`, an event starting at 18800 ms declares
 * 7160 ms of duration while the next one starts at 21800 ms. Emitted verbatim,
 * three or four cues are on screen simultaneously and libass stacks them.
 *
 * **The rule, in order:**
 *
 *  1. **Clamp** each cue's end to the next cue's start. The declared duration is
 *     how long the *window* holds the line, not how long the line is the current
 *     one, and the clamp is what converts the former into the latter.
 *  2. **Merge forward** any cue left shorter than [MIN_CUE_MS] into the one after
 *     it, up to [MAX_MERGED_CHARS] and [MAX_MERGED_MS]. Both bounds matter: without
 *     the character cap a silent passage merges a paragraph onto one line, and
 *     without the time cap a merged cue outlives the speech it transcribes.
 *  3. **Keep** everything else as it arrived.
 *
 * Word-level `offsetMs` survives all of it, rebased onto the merged cue's start,
 * so nothing here forecloses karaoke.
 *
 * Manual tracks never reach this function — they are already cue-level and
 * correctly timed, and re-grouping them would move timings YouTube got right.
 */
export function groupAsrCues(cues: Cue[]): Cue[] {
  if (cues.length === 0) return [];

  const clamped: Cue[] = [];
  for (let i = 0; i < cues.length; i++) {
    const cue = cues[i]!;
    const next = cues[i + 1];
    const endMs = next ? Math.min(cue.endMs, next.startMs) : cue.endMs;
    // A zero- or negative-length cue is a window bookkeeping artefact that
    // survived the parser, not a line. Dropping it here rather than emitting a
    // degenerate ASS event keeps the renderer from having to have an opinion.
    if (endMs > cue.startMs) clamped.push({ ...cue, endMs });
  }

  const out: Cue[] = [];
  for (const cue of clamped) {
    const previous = out[out.length - 1];
    if (
      previous !== undefined &&
      previous.endMs - previous.startMs < MIN_CUE_MS &&
      previous.endMs === cue.startMs &&
      cueText(previous).length + 1 + cueText(cue).length <= MAX_MERGED_CHARS &&
      cue.endMs - previous.startMs <= MAX_MERGED_MS
    ) {
      const shift = cue.startMs - previous.startMs;
      out[out.length - 1] = {
        startMs: previous.startMs,
        endMs: cue.endMs,
        // A space between, unless one side already supplies the separator.
        // YouTube's ASR segments carry their own leading space (" no", " to"),
        // so joining blindly doubles it on some pairs and not others.
        segments: [
          ...previous.segments,
          ...(needsSpace(previous, cue) ? [{ text: ' ', offsetMs: null }] : []),
          ...cue.segments.map((segment) => ({
            text: segment.text,
            offsetMs: segment.offsetMs === null ? null : segment.offsetMs + shift,
          })),
        ],
        style: previous.style,
      };
      continue;
    }
    out.push(cue);
  }
  return out;
}

function needsSpace(previous: Cue, next: Cue): boolean {
  const left = cueText(previous);
  const right = cueText(next);
  if (left === '' || right === '') return false;
  return !/\s$/.test(left) && !/^\s/.test(right);
}

// ---------------------------------------------------------------------------
// Normalisation
// ---------------------------------------------------------------------------

/**
 * The last thing every track goes through, grouped or not.
 *
 * Sorts by start time, drops cues with no visible text, and gives a cue with no
 * usable end one: a final cue whose duration YouTube omitted would otherwise be
 * zero-length and never appear. Ordering is enforced rather than assumed because
 * [groupAsrCues]'s clamp reads `cues[i + 1]` and a single out-of-order event
 * would make it clamp against the wrong neighbour — silently, and only for that
 * one line.
 */
export function normalizeCues(cues: Cue[]): Cue[] {
  const sorted = [...cues].sort((a, b) => a.startMs - b.startMs);
  const out: Cue[] = [];
  for (const cue of sorted) {
    if (cueText(cue).trim() === '') continue;
    const endMs = cue.endMs > cue.startMs ? cue.endMs : cue.startMs + DEFAULT_CUE_MS;
    out.push({ ...cue, endMs });
  }
  return out;
}

/** What a cue with no declared duration gets. Long enough to read, short enough not to linger. */
const DEFAULT_CUE_MS = 3000;
